name: cache-dependencies
description: node_modules cache

runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}